name: Release Cut

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/validate_action_runner.yml
    with:
      environment: "prod"

  release:
    needs: validate
    name: Release Cut
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure github
        run: |
          git config user.email "samuel.son@google.com"
          git config user.name "smsonites"

      - name: Get latest tag
        if: ${{ github.ref_name == 'main' }}
        run: |
          git fetch --tags
          TAG="$(git tag -l --sort=-v:refname | head -n 1 | cut -c2- )"
        id: version

      - name: Bump version
        run: |
          node scripts/release-cut.js ${{ github.ref_name }} ${{steps.version.outputs.TAG }}
          version=$(node -e "console.log(require('./package.json').version)")
          git add .
          git commit -m "Release v$version"
          git tag v$version
          git push origin v$version

      - name: Create release branch
        if: ${{ github.ref_name == 'main' }}
        run: |
          version=$(node -e "console.log(require('./package.json').version)")
          git branch release/${version%.*}
          git push origin release/${version%.*}

      - name: Update release branch
        if: ${{ startsWith(github.ref_name, 'release') }}
        run: |
          version=$(node -e "console.log(require('./package.json').version)")
          git push origin release/${version%.*}