name: Release Cut

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:

  validate:
    name: Validation
    runs-on: ubuntu-latests
    steps:
      - uses: ./.github/workflows/validate_action_runner.yml
        with:
          environment: "prod"

  release:
    needs: validate
    name: Release Cut
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bump version
        run: |
          node scripts/release-cut.js ${{ github.ref_name }}
          version=$(node -e "console.log(require('./package.json').version)")
          git add .
          git commit -m "Release v$version"
          git tag v$version
          git push origin v$version

      - name: Create release branch
        if: ${{ github.ref_name == 'main' }}
        run: |
          version=$(node -e "console.log(require('./package.json').version)")
          git branch release/${version%.*}
          git push origin release/${version%.*}

      - name: Update release branch
        if: ${{ startsWith(github.ref_name, 'release') }}
        run: |
          version=$(node -e "console.log(require('./package.json').version)")
          git push origin release/${version%.*}