name: Release Cut

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/validate_action_runner.yml
    with:
      environment: "prod"

  release:
    needs: validate
    name: Release Cut
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Check branch for release cut
        if: ${{ github.ref_name != 'main' || !startsWith(github.ref_name, 'release') }}
        run: |
          echo "branch ${{ github.ref_name }} cannot be used for release cut"
          exit 1

      - name: Configure github
        run: |
          git config user.email "samuel.son@google.com"
          git config user.name "smsonites"

      - name: Get latest tag
        if: ${{ github.ref_name == 'main' }}
        run: |
          git fetch --tags

          TAG_VALUE="$(git tag -l --sort=-v:refname | head -n 1 | cut -c2- )"
          echo "TAG=$TAG_VALUE" >> $GITHUB_ENV

      - name: Bump version and create Tag
        run: |
          echo "fetched version tag is $TAG"    

          node scripts/release-cut.js ${{ github.ref_name }} $TAG
          version=$(node -e "console.log(require('./package.json').version)")
          git add .
          git commit -m "Release v$version"
          git tag v$version
          git push origin v$version

          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create release branch
        if: ${{ github.ref_name == 'main' }}
        run: |
          git branch release/${VERSION%.*}
          git push origin release/${VERSION%.*}

      - name: Update release branch
        if: ${{ startsWith(github.ref_name, 'release') }}
        run: |
          git push origin release/${VERSION%.*}