name: Latest Tag test

on:
  workflow_dispatch:

jobs:
  get-latest-tag:
    name: get tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Fetch tags
        run: git fetch --tags

      - name: get tag
        run: |
          git tag -l --sort=-v:refname

          TAG_VALUE="$(git tag -l --sort=-v:refname | head -n 1 | cut -c2- )"
          echo "TAG=$TAG_VALUE" >> $GITHUB_ENV

      - name: print tag
        run: |
          echo "$TAG"
      