name: Latest Tag test

on:
  workflow_dispatch:

jobs:
  get-latest-tag:
    name: get tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Fetch tags
        run: git fetch --tags

      - name: get tag
        run: |
          TAG="$(git tag -l --sort=-v:refname | head -n 1 | cut -c2- )"
        id: version

      - name: print tag
        run: |
          echo ${{ steps.version.outputs.TAG }}
      