name: Require FR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
      - 'release/*'

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/require-checklist-action@v2
        if: ${{ !startsWith(github.head_ref, 'merge/') }}
        with:
          requireChecklist: true
