name: Require FR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
      - 'release/*'

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch exists
        id: check_branch
        run: |
          echo "Checking to see if branch exists"
          echo "Ref name: ${{ github.ref_name }}"
          result=`gh api /repos/samsonites89/gha-test/branches/${{ github.ref_name }}`
          if [[ "$result" != "" ]]
          then
            echo "Branch ${{ github.ref_name }} exists"
            echo "::set-output name=branch_exists::true"
          fi

          echo "Branch ${{ github.ref_name }} does not exist"
          echo "::set-output name=branch_exists::false"
        env:
          GH_TOKEN: ${{ secrets.PA_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}

      - uses: mheap/require-checklist-action@v2
        name: Require FR Checklist
        if: ${{ steps.check_branch.outputs.branch_exists == 'true' && !startsWith(github.head_ref, 'merge/') }}
        with:
          requireChecklist: true
