name: deploy to node

on:
  workflow_run:
    workflows: [Validate]
    types:
      - completed
    branches: [main]


jobs:
  finish:
    runs-on: ubuntu-latest
    steps:
      - name: step 2
        run: echo "SUCCESSFUL"
 
