name: Validate Github Action Runner

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  validate-action-runner:
    runs-on: ubuntu-latest
    steps:
      - name: print action runner
        run: echo $GITHUB_ACTOR


